version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: rw_user
      POSTGRES_PASSWORD: rw_pwd
      POSTGRES_DB: railway
    ports:
      - "5436:5432"
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data