version: '3'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: cw_user
      POSTGRES_PASSWORD: cw_pwd
      POSTGRES_DB: railway
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: